<?php

namespace Database\Seeders;

use App\Models\Borey;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class BoreySeeder extends Seeder
{
    /**
     * 
     * Run the command seeds.
     * php artisan db:seed --class=BoreySeeder
     *
     * @return void
     */
    public function run()
    {
        $boreyNames = [
            '5 Star Residence', '8L Villa', 'A Ressorts Villa', 'Agile Sky Residence', 'Akaschar', 'Angkor Oudom', 'Angkor Phnom Penh', 'Arakava Condo', 'Arata Garden Residence', 'Aurora City of Light', 'Blue Diamond The River', 'Boramy', 'borey', 'BTS', 'Bun Ches', 'Bun Ches 1', 'Bun Ches 2', 'Bunly', 'C & T Villa', 'Camko City', 'Chaktomuk City 2', 'Chaktumuk City 2', 'Chan Castle', 'Chan LongDy', 'Chan Sovann Residence', 'Chea Ry The Green Ville', 'Chenda Villa', 'Cheu Pom', 'Chey Oudom', 'Chey Oudom Project 10', 'Chhuk Meas', 'Chhuk Va II', 'Chhuk Va Modern Residence', 'Chip Mong Chamkar Dong', 'Chip Mong Land', 'Chip Mong Land Mark 271', 'Chip Mong Land Sen Sok', 'Chip Mong Land Toul Pongro', 'Chip Mong Park Land', 'City Villa', 'CKL Flat House', 'CRV', 'Crystal', 'CS Project 03', 'Dara Samnang', 'De Castle', 'Developer SM Land', 'Diamond Home', 'DL Residence', 'DM Flat House', 'DM II', 'Duong Ngeap Toul Pongro', 'DV Residence', 'East Land and Home', 'Flat House Taing Vutha', 'Galaxy 11', 'Garnet', 'GCCITY', 'Gold & Diamond', 'Gold Home', 'Gold Home Project 4', 'Golden Avenue', 'Golden World International Residence', 'Green Town', 'H Project 02', 'H Residence', 'Hak Cheng', 'Hak Ly', 'Harmonia', 'HBL', 'HBL Prey Tea', 'Hen Pheach', 'Heng Heang', 'Heng Huot Residence', 'Heng Kao', 'Heng Kheang', 'Heng Na', 'Heng Try', 'Hi Tech Luxury', 'Highland City', 
            'Hi-Tech 1', 'HL', 'HM Amatak', 'Hok Chheng', 'Hok Lay', 'Hok Ly', 'Hong Chheang', 'Hong Lay', 'Hong Lay Toul Pongro', 'Hong Leng Yi', 'Hong Leng Yi 1', 'Hong Leng Yi II', 'Hong Ly', 'HP Residence', 'IC', 'IC Toul Pongro', 'J&C', 'JL', 'Kamboul City', 'Kata', 'KBC & LCH', 'KC', 'KC Trust', 'Keang Hort', 'Keang Hort Rumchek', 'Keat Heng', 'Keat Hort', 'Keo Chhunny', 'Kete Phume', 'KH Residence', 'Kheam Channa', 'Kheam Channa II', 'Kheam Panha', 'Kheang Hort', 'Khit Chheurn', 'Kim Pav', 'Kim Po', 'Kim Thy', 'Kim Try III', 'Kimpo', 'Kimsan Residence', 'King Villa', 'KM Villa', 'KN', 'KP Morn Dany', 'KS Residence', 'KSR III', 'L BKK1', 'L BKK3', 'L Village Residence', 'La Pham', 'La Sen Sok', 'La Village Residence', 'Laar Penh Chet', 'Laar Pit', 'Lay Kong', 'Lay Nguon', 'Leap Samnang', 'Lem Cheang Hak', 'Leng Chhun', 'Leng Navatra', 'Leng Navatra Project 6&7', 'Leng Nimol', 'Lim Chheang Hak', 'Lim Chheang Hak 5', 'Lim Chheang Hak Chamkar Dong', 'Lim Chheang Hak Chaom Chao', 'Lim Chheang Hak Kamboul', 'Lim Chheang Hak Ou Dem II', 'Lim Chheang Hak Veal Sbov', 'Lim Chheang Hor', 'Lim Heang Hak', 'Lim Tech Heng', 'LJ Veng Sreng', 'LK', 'LK Residence', 'Long Chandy', 'Long Dy', 'Long Ny', 'Long Ny Chamkar Dong', 'Long Ny II', 'Long Ny Project 3', 'Long Ny Project II', 'Lorn City Lutussana', 'LP Residence', 'LU Signature Home', 'Luck One', 'LV Grand Park',
            'Ly Navuth', 'Ly Rany', 'Ly Sovann', 'Mekong Royal', 'Meoun Chey', 'MH', 'ML Mongkul Realty', 'ML Vimean Mongkul', 'Modelo', 'Modern House 01', 'Modern House Chhuk Va', 'Modern MH 254', 'Modern Villa 01', 'Modern Villa 01 Project 4', 'Moha Chhun Sousdey', 'Moha Saen Sokh', 'Moha Samnang', 'Moha Sok San', 'Mom Channa', 'Mongkol Phnom Penh', 'Mongkol Phnom Penh 5', 'Mongkol Phnom Penh Project 3', 'Mongkol Phnom Penh Project 4', 'Mongkol Phnom Penh Project 5', 'Mongkul Pit', 'Monorom Prek Taten', 'Morn Dany', 'Morn Dany Project 16', 'Morn Dany Project 22', 'Morn Dany Project 26', 'Morn Dany Project 4', 'Morokot Landmarks', 'Moung Neuon', 'MS', 'Muk Chamroeun', 'N/A', 'New Town', 'New World', 'New World  Takhmao', 'New World 2', 'New World Boeng Chhuk', 'New World Chamkar Dong', 'New World Chamkar Dong 1', 'New World Chamkar Dong 2', 'New World Chamkar Dong 3', 'New World Chamkar Dong New Project', 'New World Chamkar Dong Project 1', 'New World Chamkar Dong Thmei', 'New World Chamkar Doung', 'New World Chhuk Meas', 'New World Chhuk Va', 'New World Chhuk Va 1', 'New World Chhuk Va 2', 'New World Chhuk Va 3', 'New World Kamboul', 'New World Kamboul 1', 'New World Kamboul 3', 'New World Kilomete Lekh 6', 'New World Kour Srov', 'New World Kour Srov 2', 'New World Kour Srov 3', 'New World NR3', 'New World Ou Dem', 'New World Phsar Deihuy', 'New World Saen Sokh', 
            'New World Ta Khmao', 'New World Ta Khmao I', 'New World Ta Khmau', 'New World Takhmao', 'New World Takhmao 1', 'New World Takhmao 2', 'New World Takhmao I', 'New World Takhmao II', 'New World Trapeang Thloeng', 'New World Tuek Thlar', 'NH Residence', 'Nirouth Chey', 'Nokor Thmei', 'OCIC', 'Oknha Doung Ngeab', 'Orkide Botanic City', 'Orkide Villa', 'Orkide Villa III', 'Ou Dem', 'Ou Dem 2', 'Ou Dem Sen Sok', 'P & K Toul Pongro', 'Pao Sokheing', 'Paris', 'Peng Houth', 'Peng Houth the Star Platinum', 'Peng Houth the Star Platinum Eco Sunrise', 'Peng Huoth Street 50M', 'Peng Huoth the Star Diamond', 'Peng Huoth the Star Emerald', 'Peng Huoth the Star Eternal', 'Peng Huoth the Star Mercurean', 'Peng Huoth the Star Mercurean 2', 'Peng Huoth the Star Munirah', 'Peng Huoth The Star Natural', 'Peng Huoth the Star Platinum Athina', 'Peng Huoth the Star Platinum Eco Delta', 'Peng Huoth the Star Platinum Eco Roman', 'Peng Huoth the Star Platinum Eternal', 'Peng Huoth the Star Platinum Palaris 2', 'Peng Huoth the Star Platinum Polaris', 'Peng Huoth the Star Platinum Polaris 1', 'Peng Huoth the Star Platinum Roseworld', 'Peng Huoth the Star Premier', 'Peng Huoth the Starlight', 'Peng Huoth, New Project', 'Phnom Meas', 'Phnom Meas Toul Pongro', 'Phnom Penh Park', 'Phnom Penh Sok San', 'Phnom Penh Thmey', 'Phnom Penh Thmey Elite Park 2', 'Phnom Penh Town', 'Phon Suy', 
            'Piphoup Reaksmey', 'Piphoup Trop Thmey', 'Por Song Hieng', 'PRS Group', 'PS', 'PT', 'PT (04)', 'PTT', 'Raminea', 'Ratana Lalin Residence', 'Ratana Lalin Residence 2', 'Ratanak Phnom Penh', 'Rathanak Phnom Penh', 'Rattanak Phnom Penh', 'Reaksmey', 'Rithy Sak', 'Romanea', 'Rumcheck Ou Dem', 'Rumcheck Toul Pongro', 'Rumchek Ou Dem', 'Rumchek Sambour', 'Rumchek Sambour Meas', 'Rumchek Toul Pongro', 'Saen Monorom', 'Saen Sokh', 'Sakura', 'Sambath Mean Heng', 'Sambath Mean Heng 2', 'Sambath Mean Heng 3', 'Sambath Meas', 'Sambath Mongkul', 'Sambuor Meas', 'Samonda 168', 'Sao Sen', 'SC', 'Serey City', 'Sim Sothear', 'SJS', 'SK Sweet Home', 'SL King Villa', 'SM Residence', 'SN Residence', 'Soerm Mary', 'Sok Chamroeun', 'Sok San', 'Sok San Project 07', 'Sok San Town', 'Sok Sreng Takhmao', 'Sokeasa', 'Song Khun', 'Sopheak Mongkul', 'Sovannary Villa', 'SP Residence', 'Srey Sovan', 'ST Residence', 'Sunny', 'Sweet House', 'Takhmao Residence', 'TBS', 'TD', 'Thai Chhunkry', 'Thai Heang', 'The CEO Residence Sen Sok', 'The Flora', 'The Golden Avenue', 'The Mekong Royal', 'The Pearl Land', 'The Philland', 'The Residence', 'The River', 'The Sanctaury City', 'The Sok San Project 7', 'The Woods', 'Thou Lorn City', 'Thy Kim Project 7', 'TK', 'TK3', 'Toul Sangke', 'Try Kim', 'Tsa', 'Tuol Pongro Residence', 'TV Star', 'Ty Leang', 'Unibuild Construction', 'Up Town Development', 
            'Uy Hong', 'Variana', 'Variana Doung Ngeap', 'Variana Sen Sok', 'Vattanak', 'Veal Sbov Residence', 'Villa Modern 01', 'Villa Santepheap', 'Villa Toul Sangkae', 'Villa Toul Sangkae Areyksat', 'Village Residence', 'Vimean Phnom Penh', 'Vimean Sakura', 'Virakpheap', 'Visota', 'VK', 'VSL', 'Williams', 'World Bridge Homes', 'Yeab Sovanna'
        ];

        foreach($boreyNames as $name) {
            Borey::create([
                'borey_name' => $name,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }
    }
}
